/**
 * Shared English strings. Plain nested strings only — this whole folder can be
 * serialized to `lt.json` and mirrored as `en.json` / `ru.json` later.
 */
type Testimonial = { name: string; country: string; quote: string; source: string };

const testimonials: Testimonial[] = [
  {
    name: "Balys",
    country: "Lithuania",
    quote: "The property is at amazing spot, you can reach amazing places on foot.",
    source: "Booking.com",
  },
  {
    name: "Anilkumar",
    country: "Switzerland",
    quote:
      "1. The apartment is spacious and clean. 2. The check-in process is easy, you just use the code given to you. 3. The owner was kind and refunded part of my stay as I needed to reduce the length of it.",
    source: "Booking.com",
  },
  {
    name: "Dominika",
    country: "Lithuania",
    quote:
      "Quiet spacious room, good location. Though they do not have parking it was very easy to find parking next to it. Had all you could need.",
    source: "Booking.com",
  },
  {
    name: "Craig",
    country: "Lithuania",
    quote: "Was clean and tidy. Staff was helpful. When we called we got help straight away.",
    source: "Booking.com",
  },
  {
    name: "Vesta",
    country: "Lithuania",
    quote:
      "Location, easy self check in, availability to sleep in different beds with a friend!",
    source: "Booking.com",
  },
  {
    name: "Marija",
    country: "Lithuania",
    quote:
      "I loved how helpful the owners were - solving one issue upon our arrival immediately. Rooms are modern and clean. There were wide selection of extra items - dental kit, even shaving kit, hot air iron - I was impressed!",
    source: "Booking.com",
  },
];

export const common = {
  brand: "Dharma Stay",
  tagline: "From home to home.",
  cta: {
    book: "Book",
    checkDates: "Check available dates",
    more: "Learn more",
    openMap: "Open in map",
    contactUs: "Contact us",
    allStays: "All apartments",
  },
  nav: {
    home: "Home",
    about: "About",
    rules: "House rules",
    stays: "Apartments",
    standard: "Standard apartments",
    terrace: "Apartments with a terrace and city-centre view",
    cottage: "Cottage with sauna and hot tub",
    restobar: "Restobar",
    banquet: "Banquet hall",
    sauna: "Sauna",
    vouchers: "Gift vouchers",
    contacts: "Contacts",
    more: "More",
    site: "Site",
  },
  labels: {
    priceFrom: "From",
    size: "Size",
    guests: "Guests",
    upTo: "up to",
    guestsLower: "guests",
    bedsLower: "beds",
    perNight: "per night",
    address: "Address",
    amenities: "Amenities",
    contacts: "Contacts",
    breadcrumb: "Breadcrumb",
    otherStays: "Other accommodation options",
  },
  stays: {
    availabilityTitle: "Available dates",
    availabilityLead:
      "Choose your check-in and check-out dates. Occupied days are marked and cannot be selected.",
    checkin: "Check-in",
    checkout: "Check-out",
    occupied: "Occupied",
    occupiedDayLabel: "Occupied day — cannot be booked",
    available: "Available",
    selected: "Selected",
    nights: "nights",
    night: "night",
    nightsMany: "nights",
    pickDates: "Choose dates",
    clearDates: "Clear",
    noOccupied: "All dates are currently available.",
    loading: "Loading…",
    errorTitle: "Failed to load apartments",
    errorText:
      "The booking system is currently unreachable. Please try again or contact us directly.",
    retry: "Try again",
    emptyTitle: "No available properties at the moment",
    emptyText:
      "The list will be updated soon. For dates and availability, please contact us directly.",
    priceOnRequest: "Price on request",
    pickProperty: "Choose accommodation",
    galleryTitle: "Photos",
  },
  booking: {
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    extras: "Extra services",
    perPerson: "per person per night",
    perChild: "per child per night",
    flatPerDay: "per night",
    nights: "Nights",
    nightlyRate: "Rate per night",
    stayTotal: "Subtotal",
    extrasTotal: "Extras total",
    total: "Total",
    calculating: "Calculating price…",
    pickDatesPrompt: "Choose your check-in and check-out dates — we'll show the price right away.",
    unavailable: "These dates are no longer available. Please choose other dates.",
    tooManyGuests: "Too many guests for this accommodation. Please reduce the number of guests.",
    badRequest: "Please check the dates and number of guests.",
    notFound: "This accommodation could no longer be found.",
    genericError: "Failed to calculate the price. Please try again.",
    submitSoon: "Booking confirmation coming soon",
    contactTitle: "Your contact details",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    bic: "Bank BIC (optional)",
    nameError: "Enter your full name (at least 2 characters).",
    emailError: "Enter a valid email address.",
    phoneError: "Enter a phone number (at least 5 characters).",
    bicError: "BIC can be up to 20 characters.",
    submit: "Book",
    submitting: "Sending…",
    datesUnavailable: "Sorry, these dates were just taken. Please choose other dates.",
    submitError: "Failed to create the booking. Please try again.",
    needQuote: "Choose your dates and wait for the price — then you'll be able to book.",
    companyToggle: "Booking on behalf of a company",
    companyTitle: "Company details",
    companyName: "Company name",
    companyCode: "Company code",
    companyVat: "VAT code (optional)",
    companyAddress: "Company address",
    companyNameError: "Enter the company name.",
    companyCodeError: "Enter the company code.",
    companyAddressError: "Enter the company address.",
    consentPrefix: "I have read and agree to the",
    consentTerms: "terms of service",
    consentAnd: "and",
    consentPrivacy: "privacy policy",
    datesLoading: "Checking availability…",
    dialogTitle: "Check availability",
    dialogDescription:
      "You are booking directly on the Dharma Stay website. Payment is by bank transfer — we show the details right after your booking.",
    stayLabel: "Accommodation",
    noCommissionNote: "Direct booking — no agents, no Booking.com commission.",
    consentError: "Please confirm your agreement to the terms to continue.",
  },
  footer: {
    intro: "Accommodation in the Telšiai old town. From home to home.",
    rights: "Bookings made directly, with no intermediaries.",
  },
  availabilityBand: {
    eyebrow: "Available dates",
    title: "Check available dates",
    lead: "Choose your check-in and check-out dates — you'll instantly see how many apartments of each type are available and how much they cost.",
    guests: "Guests",
    pickDates: "Choose your check-in and check-out dates.",
    checking: "Checking available dates…",
    freeOne: "available",
    freeFew: "available",
    freeMany: "available",
    none: "None available",
    ofTotal: "of",
    priceFor: "for",
    error: "Failed to check available dates. Please try again.",
    retry: "Try again",
    reset: "Clear dates",
  },
  categories: {
    standard: "Standard apartments",
    terrace: "Apartments with a terrace",
    cottage: "Cottage with sauna and hot tub",
  },
  categoryCard: {
    viewOptions: "View options",
    optionsOne: "option",
    optionsFew: "options",
    optionsMany: "options",
  },
  search: {
    eyebrow: "Telsiai · Samogitia",
    title: "Apartments in the old town of Telsiai",
    lead: "Pick your dates and guests — we'll show what is available right away.",
    datesLabel: "Dates",
    datesPlaceholder: "Check-in — check-out",
    guestsLabel: "Guests",
    submit: "Search",
    clear: "Clear",
    done: "Done",
    nightOne: "night",
    nightFew: "nights",
    nightMany: "nights",
    adults: "Adults",
    adultsHint: "13+",
    children: "Children",
    childrenHint: "2–12 yrs",
    infants: "Infants",
    infantsHint: "under 2",
    adultOne: "adult",
    adultFew: "adults",
    adultMany: "adults",
    childOne: "child",
    childFew: "children",
    childMany: "children",
    infantOne: "infant",
    infantFew: "infants",
    infantMany: "infants",
    needDates: "Choose dates",
    checkIn: "Check-in",
    checkOut: "Check-out",
    nightsLabel: "Nights",

  },
  results: {
    seoTitle: "Available rooms — Dharma Stay",
    seoDescription:
      "Dharma Stay apartments and cottage available on your dates in Telsiai. Book directly, without intermediaries.",
    eyebrow: "Available rooms",
    title: "Available on your dates",
    missingDates: "Choose check-in and check-out dates and we'll show what is available.",
    loading: "Checking availability…",
    empty: "No rooms available on these dates",
    emptyHint: "Try other dates or reduce the number of guests.",
    error: "Could not check availability.",
    retry: "Try again",
    forStay: "for the whole stay",
    perNight: "per night",
    openGallery: "View photos",
    closeGallery: "Close",
    prev: "Previous",
    next: "Next",
    foundOne: "room available",
    foundFew: "rooms available",
    foundMany: "rooms available",
    moreInfo: "More",
    lessInfo: "Close",
    detailsTitle: "Room details",
    amenitiesTitle: "Room amenities",
  },
  testimonials: {
    eyebrow: "Booking.com reviews",
    title: "What guests say",
    prev: "Previous reviews",
    next: "Next reviews",
    items: testimonials,
  },
};
