/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminHousekeepingRouteImport } from './routes/_authenticated/admin.housekeeping'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated/admin.units'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as ApiPublicNotificationsCronRouteImport } from './routes/api/public/notifications-cron'
import { Route as AuthenticatedAdminUnitsIdRouteImport } from './routes/_authenticated/admin.units.$id'
import { Route as ApiPublicV1LegalRouteImport } from './routes/api/public/v1/legal'
import { Route as ApiPublicV1PaymentDetailsRouteImport } from './routes/api/public/v1/payment-details'
import { Route as ApiPublicV1PropertiesRouteImport } from './routes/api/public/v1/properties'
import { Route as ApiStaffV1RoomsRouteImport } from './routes/api/staff/v1/rooms'
import { Route as ApiPublicV1PropertiesIdRouteImport } from './routes/api/public/v1/properties.$id'
import { Route as ApiStaffV1RoomsIdAssignRouteImport } from './routes/api/staff/v1/rooms.$id.assign'
import { Route as ApiStaffV1RoomsIdCommentsRouteImport } from './routes/api/staff/v1/rooms.$id.comments'
import { Route as ApiStaffV1RoomsIdIssueRouteImport } from './routes/api/staff/v1/rooms.$id.issue'
import { Route as ApiStaffV1RoomsIdStatusRouteImport } from './routes/api/staff/v1/rooms.$id.status'
import { Route as ApiStaffV1RoomsIdUnassignRouteImport } from './routes/api/staff/v1/rooms.$id.unassign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHousekeepingRoute =
  AuthenticatedAdminHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const ApiPublicNotificationsCronRoute =
  ApiPublicNotificationsCronRouteImport.update({
    id: '/api/public/notifications-cron',
    path: '/api/public/notifications-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUnitsIdRoute =
  AuthenticatedAdminUnitsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUnitsRoute,
  } as any)
const ApiPublicV1LegalRoute = ApiPublicV1LegalRouteImport.update({
  id: '/api/public/v1/legal',
  path: '/api/public/v1/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PaymentDetailsRoute =
  ApiPublicV1PaymentDetailsRouteImport.update({
    id: '/api/public/v1/payment-details',
    path: '/api/public/v1/payment-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PropertiesRoute = ApiPublicV1PropertiesRouteImport.update({
  id: '/api/public/v1/properties',
  path: '/api/public/v1/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffV1RoomsRoute = ApiStaffV1RoomsRouteImport.update({
  id: '/api/staff/v1/rooms',
  path: '/api/staff/v1/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PropertiesIdRoute = ApiPublicV1PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PropertiesRoute,
} as any)
const ApiStaffV1RoomsIdAssignRoute = ApiStaffV1RoomsIdAssignRouteImport.update({
  id: '/$id/assign',
  path: '/$id/assign',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdCommentsRoute =
  ApiStaffV1RoomsIdCommentsRouteImport.update({
    id: '/$id/comments',
    path: '/$id/comments',
    getParentRoute: () => ApiStaffV1RoomsRoute,
  } as any)
const ApiStaffV1RoomsIdIssueRoute = ApiStaffV1RoomsIdIssueRouteImport.update({
  id: '/$id/issue',
  path: '/$id/issue',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdStatusRoute = ApiStaffV1RoomsIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdUnassignRoute =
  ApiStaffV1RoomsIdUnassignRouteImport.update({
    id: '/$id/unassign',
    path: '/$id/unassign',
    getParentRoute: () => ApiStaffV1RoomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/en/': typeof EnIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/admin/units/$id': typeof AuthenticatedAdminUnitsIdRoute
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en': typeof EnIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/admin/units/$id': typeof AuthenticatedAdminUnitsIdRoute
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/en': typeof EnRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/en/': typeof EnIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/admin/units/$id': typeof AuthenticatedAdminUnitsIdRoute
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/staff'
    | '/en/'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/housekeeping'
    | '/admin/invoices'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/units'
    | '/admin/users'
    | '/staff/$id'
    | '/api/public/notifications-cron'
    | '/admin/'
    | '/staff/'
    | '/admin/units/$id'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/staff/v1/rooms'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/en'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/housekeeping'
    | '/admin/invoices'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/units'
    | '/admin/users'
    | '/staff/$id'
    | '/api/public/notifications-cron'
    | '/admin'
    | '/staff'
    | '/admin/units/$id'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/staff/v1/rooms'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/en'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/en/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/housekeeping'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/units'
    | '/_authenticated/admin/users'
    | '/_authenticated/staff/$id'
    | '/api/public/notifications-cron'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
    | '/_authenticated/admin/units/$id'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/staff/v1/rooms'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EnRouteRoute: typeof EnRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicNotificationsCronRoute: typeof ApiPublicNotificationsCronRoute
  ApiPublicV1LegalRoute: typeof ApiPublicV1LegalRoute
  ApiPublicV1PaymentDetailsRoute: typeof ApiPublicV1PaymentDetailsRoute
  ApiPublicV1PropertiesRoute: typeof ApiPublicV1PropertiesRouteWithChildren
  ApiStaffV1RoomsRoute: typeof ApiStaffV1RoomsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/housekeeping': {
      id: '/_authenticated/admin/housekeeping'
      path: '/housekeeping'
      fullPath: '/admin/housekeeping'
      preLoaderRoute: typeof AuthenticatedAdminHousekeepingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/api/public/notifications-cron': {
      id: '/api/public/notifications-cron'
      path: '/api/public/notifications-cron'
      fullPath: '/api/public/notifications-cron'
      preLoaderRoute: typeof ApiPublicNotificationsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/units/$id': {
      id: '/_authenticated/admin/units/$id'
      path: '/$id'
      fullPath: '/admin/units/$id'
      preLoaderRoute: typeof AuthenticatedAdminUnitsIdRouteImport
      parentRoute: typeof AuthenticatedAdminUnitsRoute
    }
    '/api/public/v1/legal': {
      id: '/api/public/v1/legal'
      path: '/api/public/v1/legal'
      fullPath: '/api/public/v1/legal'
      preLoaderRoute: typeof ApiPublicV1LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/payment-details': {
      id: '/api/public/v1/payment-details'
      path: '/api/public/v1/payment-details'
      fullPath: '/api/public/v1/payment-details'
      preLoaderRoute: typeof ApiPublicV1PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/properties': {
      id: '/api/public/v1/properties'
      path: '/api/public/v1/properties'
      fullPath: '/api/public/v1/properties'
      preLoaderRoute: typeof ApiPublicV1PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/v1/rooms': {
      id: '/api/staff/v1/rooms'
      path: '/api/staff/v1/rooms'
      fullPath: '/api/staff/v1/rooms'
      preLoaderRoute: typeof ApiStaffV1RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/properties/$id': {
      id: '/api/public/v1/properties/$id'
      path: '/$id'
      fullPath: '/api/public/v1/properties/$id'
      preLoaderRoute: typeof ApiPublicV1PropertiesIdRouteImport
      parentRoute: typeof ApiPublicV1PropertiesRoute
    }
    '/api/staff/v1/rooms/$id/assign': {
      id: '/api/staff/v1/rooms/$id/assign'
      path: '/$id/assign'
      fullPath: '/api/staff/v1/rooms/$id/assign'
      preLoaderRoute: typeof ApiStaffV1RoomsIdAssignRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/comments': {
      id: '/api/staff/v1/rooms/$id/comments'
      path: '/$id/comments'
      fullPath: '/api/staff/v1/rooms/$id/comments'
      preLoaderRoute: typeof ApiStaffV1RoomsIdCommentsRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/issue': {
      id: '/api/staff/v1/rooms/$id/issue'
      path: '/$id/issue'
      fullPath: '/api/staff/v1/rooms/$id/issue'
      preLoaderRoute: typeof ApiStaffV1RoomsIdIssueRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/status': {
      id: '/api/staff/v1/rooms/$id/status'
      path: '/$id/status'
      fullPath: '/api/staff/v1/rooms/$id/status'
      preLoaderRoute: typeof ApiStaffV1RoomsIdStatusRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/unassign': {
      id: '/api/staff/v1/rooms/$id/unassign'
      path: '/$id/unassign'
      fullPath: '/api/staff/v1/rooms/$id/unassign'
      preLoaderRoute: typeof ApiStaffV1RoomsIdUnassignRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
  }
}

interface AuthenticatedAdminUnitsRouteChildren {
  AuthenticatedAdminUnitsIdRoute: typeof AuthenticatedAdminUnitsIdRoute
}

const AuthenticatedAdminUnitsRouteChildren: AuthenticatedAdminUnitsRouteChildren =
  {
    AuthenticatedAdminUnitsIdRoute: AuthenticatedAdminUnitsIdRoute,
  }

const AuthenticatedAdminUnitsRouteWithChildren =
  AuthenticatedAdminUnitsRoute._addFileChildren(
    AuthenticatedAdminUnitsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminHousekeepingRoute: typeof AuthenticatedAdminHousekeepingRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminHousekeepingRoute: AuthenticatedAdminHousekeepingRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnRouteRouteChildren {
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnIndexRoute: EnIndexRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface ApiPublicV1PropertiesRouteChildren {
  ApiPublicV1PropertiesIdRoute: typeof ApiPublicV1PropertiesIdRoute
}

const ApiPublicV1PropertiesRouteChildren: ApiPublicV1PropertiesRouteChildren = {
  ApiPublicV1PropertiesIdRoute: ApiPublicV1PropertiesIdRoute,
}

const ApiPublicV1PropertiesRouteWithChildren =
  ApiPublicV1PropertiesRoute._addFileChildren(
    ApiPublicV1PropertiesRouteChildren,
  )

interface ApiStaffV1RoomsRouteChildren {
  ApiStaffV1RoomsIdAssignRoute: typeof ApiStaffV1RoomsIdAssignRoute
  ApiStaffV1RoomsIdCommentsRoute: typeof ApiStaffV1RoomsIdCommentsRoute
  ApiStaffV1RoomsIdIssueRoute: typeof ApiStaffV1RoomsIdIssueRoute
  ApiStaffV1RoomsIdStatusRoute: typeof ApiStaffV1RoomsIdStatusRoute
  ApiStaffV1RoomsIdUnassignRoute: typeof ApiStaffV1RoomsIdUnassignRoute
}

const ApiStaffV1RoomsRouteChildren: ApiStaffV1RoomsRouteChildren = {
  ApiStaffV1RoomsIdAssignRoute: ApiStaffV1RoomsIdAssignRoute,
  ApiStaffV1RoomsIdCommentsRoute: ApiStaffV1RoomsIdCommentsRoute,
  ApiStaffV1RoomsIdIssueRoute: ApiStaffV1RoomsIdIssueRoute,
  ApiStaffV1RoomsIdStatusRoute: ApiStaffV1RoomsIdStatusRoute,
  ApiStaffV1RoomsIdUnassignRoute: ApiStaffV1RoomsIdUnassignRoute,
}

const ApiStaffV1RoomsRouteWithChildren = ApiStaffV1RoomsRoute._addFileChildren(
  ApiStaffV1RoomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EnRouteRoute: EnRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicNotificationsCronRoute: ApiPublicNotificationsCronRoute,
  ApiPublicV1LegalRoute: ApiPublicV1LegalRoute,
  ApiPublicV1PaymentDetailsRoute: ApiPublicV1PaymentDetailsRoute,
  ApiPublicV1PropertiesRoute: ApiPublicV1PropertiesRouteWithChildren,
  ApiStaffV1RoomsRoute: ApiStaffV1RoomsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
