/**
 * Shared Lithuanian strings. Plain nested strings only — this whole folder can be
 * serialized to `lt.json` and mirrored as `en.json` / `ru.json` later.
 */
type Testimonial = { name: string; country: string; quote: string; source: string };

const testimonials: Testimonial[] = [
  {
    name: "Solveiga",
    country: "Lietuva",
    quote:
      "Ir antras kartas nenuvylė. Kambarys tvarkingas, jaukus. Yra visko, ko reikia viešnagei.",
    source: "Booking.com",
  },
  {
    name: "Giedrė",
    country: "Lietuva",
    quote:
      "Labai patogi vieta, švarus ir gražūs apartamentai, radom visas reikalingas higienos priemones.",
    source: "Booking.com",
  },
  {
    name: "Erika",
    country: "Danija",
    quote:
      "Nuomojamės kambarį trims žmonėms, ir viskas patiko! Lovos patogios, pagalvės patogios, gražūs patogūs vonios kambarys. Virtuvytė maža bet visko ko reik lengvam gaminimui. Gražus vaizdas pro langą.",
    source: "Booking.com",
  },
];

export const common = {
  brand: "Dharma Stay",
  tagline: "Iš namų į namus.",
  cta: {
    book: "Rezervuoti",
    checkDates: "Tikrinti laisvas datas",
    more: "Plačiau",
    openMap: "Atidaryti žemėlapyje",
    contactUs: "Susisiekti",
    allStays: "Visi apartamentai",
  },
  nav: {
    home: "Pagrindinis",
    about: "Apie",
    rules: "Apgyvendinimo taisyklės",
    stays: "Apartamentai",
    standard: "Standartiniai apartamentai",
    terrace: "Apartamentai su terasa ir vaizdu į miesto centrą",
    cottage: "Namelis su pirtimi ir kubilu",
    restobar: "Restobaras",
    banquet: "Banketinė salė",
    sauna: "Sauna",
    vouchers: "Dovanų kuponai",
    contacts: "Kontaktai",
    more: "Daugiau",
    site: "Svetainė",
  },
  labels: {
    priceFrom: "Nuo",
    size: "Dydis",
    guests: "Svečiai",
    upTo: "iki",
    guestsLower: "svečių",
    bedsLower: "lovos",
    perNight: "nakčiai",
    address: "Adresas",
    amenities: "Patogumai",
    contacts: "Kontaktai",
    otherStays: "Kiti apgyvendinimo variantai",
    breadcrumb: "Naršymo kelias",
  },
  stays: {
    availabilityTitle: "Laisvos datos",
    availabilityLead:
      "Pasirinkite atvykimo ir išvykimo datas. Užimtos dienos pažymėtos ir nepasirenkamos.",
    checkin: "Atvykimas",
    checkout: "Išvykimas",
    occupied: "Užimta",
    occupiedDayLabel: "Užimta diena – rezervuoti negalima",
    available: "Laisva",
    selected: "Pasirinkta",
    nights: "naktys",
    night: "naktis",
    nightsMany: "naktų",
    pickDates: "Pasirinkite datas",
    clearDates: "Išvalyti",
    noOccupied: "Šiuo metu visos datos laisvos.",
    loading: "Kraunama…",
    errorTitle: "Nepavyko įkelti apartamentų",
    errorText:
      "Šiuo metu nepavyksta pasiekti rezervacijų sistemos. Pabandykite dar kartą arba susisiekite tiesiogiai.",
    retry: "Bandyti dar kartą",
    emptyTitle: "Šiuo metu laisvų objektų nėra",
    emptyText:
      "Sąrašas netrukus bus atnaujintas. Dėl datų ir galimybių susisiekite su mumis tiesiogiai.",
    priceOnRequest: "Kaina pagal užklausą",
    pickProperty: "Pasirinkite apgyvendinimą",
    galleryTitle: "Nuotraukos",
  },
  booking: {
    adults: "Suaugusieji",
    children: "Vaikai",
    infants: "Kūdikiai",
    extras: "Papildomos paslaugos",
    perPerson: "asmeniui už parą",
    perChild: "vaikui už parą",
    flatPerDay: "už parą",
    nights: "Naktys",
    nightlyRate: "Kaina už naktį",
    stayTotal: "Tarpinė suma",
    extrasTotal: "Paslaugos iš viso",
    total: "Iš viso",
    calculating: "Skaičiuojama kaina…",
    pickDatesPrompt: "Pasirinkite atvykimo ir išvykimo datas – kainą parodysime iš karto.",
    unavailable: "Šios datos nebelaisvos. Pasirinkite kitas datas.",
    tooManyGuests: "Pasirinktam apgyvendinimui per daug svečių. Sumažinkite svečių skaičių.",
    badRequest: "Patikrinkite datas ir svečių skaičių.",
    notFound: "Šio apgyvendinimo nebepavyko rasti.",
    genericError: "Nepavyko apskaičiuoti kainos. Pabandykite dar kartą.",
    submitSoon: "Rezervacijos patvirtinimas netrukus",
    contactTitle: "Jūsų kontaktai",
    name: "Vardas ir pavardė",
    email: "El. paštas",
    phone: "Telefonas",
    bic: "Banko BIC (nebūtina)",
    nameError: "Įveskite vardą ir pavardę (bent 2 simboliai).",
    emailError: "Įveskite teisingą el. pašto adresą.",
    phoneError: "Įveskite telefono numerį (bent 5 simboliai).",
    bicError: "BIC gali būti iki 20 simbolių.",
    submit: "Rezervuoti",
    submitting: "Siunčiama…",
    datesUnavailable: "Deja, šios datos ką tik buvo užimtos. Pasirinkite kitas datas.",
    submitError: "Nepavyko sukurti rezervacijos. Pabandykite dar kartą.",
    needQuote: "Pasirinkite datas ir palaukite kainos – tada galėsite rezervuoti.",
    companyToggle: "Užsakau įmonės vardu",
    companyTitle: "Įmonės duomenys",
    companyName: "Įmonės pavadinimas",
    companyCode: "Įmonės kodas",
    companyVat: "PVM mokėtojo kodas (nebūtina)",
    companyAddress: "Įmonės adresas",
    companyNameError: "Įveskite įmonės pavadinimą.",
    companyCodeError: "Įveskite įmonės kodą.",
    companyAddressError: "Įveskite įmonės adresą.",
    consentPrefix: "Susipažinau ir sutinku su",
    consentTerms: "paslaugų teikimo taisyklėmis",
    consentAnd: "ir",
    consentPrivacy: "privatumo politika",
    consentError: "Norėdami tęsti, patvirtinkite sutikimą su taisyklėmis.",
    datesLoading: "Tikriname laisvas datas…",
    dialogTitle: "Tikrinti laisvas datas",
    dialogDescription:
      "Rezervacija vyksta čia, Dharma Stay svetainėje. Apmokėjimas – banko pavedimu, rekvizitus parodysime iš karto po rezervacijos.",
    stayLabel: "Apgyvendinimas",
    noCommissionNote: "Be tarpininkų ir be Booking.com komisinių.",
  },
  footer: {
    intro: "Apgyvendinimas Telšių senamiestyje. Iš namų į namus.",
    rights: "Rezervacijos tiesiogiai, be tarpininkų.",
  },
  availabilityBand: {
    eyebrow: "Laisvos datos",
    title: "Pasitikrinkite laisvas datas",
    lead: "Pasirinkite atvykimo ir išvykimo datas — iš karto matysite, kiek kurio tipo apartamentų laisva ir kiek kainuos.",
    guests: "Svečiai",
    pickDates: "Pasirinkite atvykimo ir išvykimo datas.",
    checking: "Tikriname laisvas datas…",
    freeOne: "laisvas",
    freeFew: "laisvi",
    freeMany: "laisvų",
    none: "Nėra laisvų",
    ofTotal: "iš",
    priceFor: "už",
    error: "Nepavyko patikrinti laisvų datų. Pabandykite dar kartą.",
    retry: "Bandyti dar kartą",
    reset: "Išvalyti datas",
  },
  categories: {
    standard: "Standartiniai apartamentai",
    terrace: "Apartamentai su terasa",
    cottage: "Namelis su pirtimi ir kubilu",
  },
  categoryCard: {
    viewOptions: "Žiūrėti variantus",
    optionsOne: "variantas",
    optionsFew: "variantai",
    optionsMany: "variantų",
  },
  search: {
    eyebrow: "Telšiai · Žemaitija",
    title: "Apartamentai Telšių senamiestyje",
    lead: "Pasirinkite datas ir svečių skaičių — iš karto parodysime, kas laisva.",
    datesLabel: "Datos",
    datesPlaceholder: "Atvykimas — išvykimas",
    guestsLabel: "Svečiai",
    submit: "Ieškoti",
    clear: "Išvalyti",
    done: "Gerai",
    nightOne: "naktis",
    nightFew: "naktys",
    nightMany: "naktų",
    adults: "Suaugę",
    adultsHint: "nuo 13 m.",
    children: "Vaikai",
    childrenHint: "2–12 m.",
    infants: "Kūdikiai",
    infantsHint: "iki 2 m.",
    adultOne: "suaugęs",
    adultFew: "suaugę",
    adultMany: "suaugusių",
    childOne: "vaikas",
    childFew: "vaikai",
    childMany: "vaikų",
    infantOne: "kūdikis",
    infantFew: "kūdikiai",
    infantMany: "kūdikių",
    needDates: "Pasirinkite datas",
    checkIn: "Atvykimas",
    checkOut: "Išvykimas",
    nightsLabel: "Naktys",

  },
  results: {
    seoTitle: "Laisvi kambariai — Dharma Stay",
    seoDescription:
      "Pasirinktomis datomis laisvi Dharma Stay apartamentai ir namelis Telšiuose. Rezervuokite tiesiogiai, be tarpininkų.",
    eyebrow: "Laisvi numeriai",
    title: "Laisvi pasirinktomis datomis",
    missingDates: "Pasirinkite atvykimo ir išvykimo datas — parodysime, kas laisva.",
    loading: "Tikriname laisvus numerius…",
    empty: "Šiomis dienomis laisvų numerių nėra",
    emptyHint: "Pabandykite kitas datas arba sumažinkite svečių skaičių.",
    error: "Nepavyko patikrinti laisvų numerių.",
    retry: "Bandyti dar kartą",
    forStay: "visam laikotarpiui",
    perNight: "nakčiai",
    openGallery: "Žiūrėti nuotraukas",
    closeGallery: "Uždaryti",
    prev: "Ankstesnė",
    next: "Kita",
    foundOne: "laisvas numeris",
    foundFew: "laisvi numeriai",
    foundMany: "laisvų numerių",
    moreInfo: "Daugiau",
    lessInfo: "Uždaryti",
    detailsTitle: "Išsami informacija",
    amenitiesTitle: "Kambario patogumai",
  },
  testimonials: {
    eyebrow: "Booking.com įvertinimai",
    title: "Ką sako svečiai",
    prev: "Ankstesni atsiliepimai",
    next: "Kiti atsiliepimai",
    items: testimonials,
  },
} as const;
